name: build-and-push-docker-image-for-colmap

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  #  https://github.com/marketplace/actions/build-and-push-docker-images#usage:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/colmap:latest
